### ISSUE TITLE
Enchantment issue with fallen knights.

### ISSUE THREAD

**Issue by Claycorp** [CrazyPants/EnderZoo#42]
http://pastebin.com/d6v2fYgs

**Comment by tterrag1098** [comment]
I think this may have been caused by a bug in EIO strangely. Could you update that to 2.2.6 latest?

**Comment by Divineaspect** [comment]
2.2.6.317?

**Comment by tterrag1098** [comment]
Yes.

**Comment by Divineaspect** [comment]
Running a spawner system with fallen knights and villagers time torched to attempt to duplicate with updated ender io, no results after about an hour.

**Comment by tterrag1098** [comment]
It was probably due then to the missing Soulbound enchant (causing bugged items) in 2.2.5 of EIO. Closing this.
