### ISSUE TITLE
Suggestion on Power Conduits

### ISSUE THREAD

**Issue by Unatan63** [CrazyPants/EnderZoo#54]
Early game one uses the low tier conduits through out their bases, once one gets to the point of upgrading the energy conduits we have a mass of useless (for the most part) low tier conduits, can't they be used in upgrading to next tier? a choice per-say of using either the lower tier if you have them or creating them from scratch? as it stands I have about 300 of the lower tier conduits just wasting away, seems so wastefull

**Comment by CrazyPants** [comment]
This should be posted here: https://github.com/CrazyPants/EnderIO/issues
