### ISSUE TITLE
Would it be possible to support Thaumcraft 4 essentia tubes in bundles?

### ISSUE THREAD

**Issue by tinkertim** [CrazyPants/EnderZoo#61]
I was piping in some essentia tubes on top of power, item, AE and redstone conduits earlier and I thought - _gosh it would be nice if I could fit some essentia tubes for these lamps of growth in this bundle too_. 

Would it be possible to support these, similarly to the way AE cables work, or perhaps make one of the existing fluid conduits work with them? It'd sure be nice for farming and automated alchemy setups.

As both TC4 and EnderIO are becoming staples in most mod packs, it'd sure be great if the two could work together more closely where possible :D

**Comment by CrazyPants** [comment]
This is posted in the wrong mod. The correct area is: https://github.com/CrazyPants/EnderIO/issues
